name: Nextflow CI
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['18.10.1','19.07.0', '']
        #aligner: ["--aligner 'hisat2'", "--aligner 'star'", "--pseudo_aligner 'salmon'"]
        #options: ['--skipQC', '--remove_rRNA', '--saveUnaligned', '--skipTrimming', '--star_index false']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Download image
        run: |
          docker pull charlottek/trimming
      - name: Basic workflow tests
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker 
      
